@startuml Diagrama de componente
allow_mixing
top to bottom direction
package "view" {
    component TransferDAWHTML <<html>>
    component TransferDAWSCSS <<css>>
    component TransferDAWJS <<javascript>>
}

package "controller" {
    component TransferDAWServlet <<servlet>>
}

TransferDAWHTML ..> TransferDAWServlet : solicita datos
TransferDAWJS ..> TransferDAWServlet : hace solicitudes dinámicas

package "model"{

    package bbdd{
        component Database <<java>>

        interface TranferDAWDAO {
            +insertar(representante: Representante): void
            +modificar(representante: Representante): void
            +eliminar(idRepresentante: int): void
            +listar(): List<Representante>

            +insertar(entrenador: Entrenador): void
            +modificar(entrenador: Entrenador): void
            +eliminar(idEntrenador: int): void
            +listar(): List<Entrenador>


            +insertar(categoriaPosicion: CategoriaPosicion): void
            +modificar(categoriaPosicion: CategoriaPosicion): void
            +eliminar(idCategoria: int): void
            +listar(): List<CategoriaPosicion>


            +insertar(posicion: Posicion): void
            +modificar(posicion: Posicion): void
            +eliminar(idPosicion: int): void
            +listar(): List<Posicion>

            +insertar(temporada: Temporada): void
            +modificar(temporada: Temporada): void
            +eliminar(idTemporada: int): void
            +listar(): List<Temporada>

            +insertar(jugador: Jugador): void
            +modificar(jugador: Jugador): void
            +eliminar(idJugador: int): void
            +listar(): List<Jugador>
            +buscarPorId(int idJugador);


            +insertar(seleccion: Seleccion): void
            +modificar(seleccion: Seleccion): void
            +eliminar(idSeleccion: int): void
            +listar(): List<Seleccion>

            +insertar(equipo: Equipo): void
            +modificar(equipo: Equipo): void
            +eliminar(idEquipo: int): void
            +listar(): List<Equipo>

            +insertar(competicion: Competicion): void
            +modificar(competicion: Competicion): void
            +eliminar(idCompeticion: int): void
            +listar(): List<Competicion>

            +insertar(equipoCompeticion: EquipoCompeticion): void
            +modificar(equipoCompeticion: EquipoCompeticion): void
            +eliminar(equipoId: int, competicionId: int, temporadaId: int): void
            +listar(): List<EquipoCompeticion>

            +insertar(contrato: Contrato): void
            +modificar(contrato: Contrato): void
            +eliminar(idContrato: int): void
            +listar(): List<Contrato>

            +insertar(estadio: Estadio): void
            +modificar(estadio: Estadio): void
            +eliminar(idEstadio: int): void
            +listar(): List<Estadio>

            +insertar(equipoEstadio: EquipoEstadio): void
            +modificar(equipoEstadio: EquipoEstadio): void
            +eliminar(equipoId: int, estadioId: int): void
            +listar(): List<EquipoEstadio>

            +insertar(jugadorPosicion: JugadorPosicion): void
            +modificar(jugadorPosicion: JugadorPosicion): void
            +eliminar(jugadorId: int, posicionId: int, temporadaId: int): void
            +listar(): List<JugadorPosicion>

            +insertar(estadisticasTemporada: EstadisticasTemporada): void
            +modificar(estadisticasTemporada: EstadisticasTemporada): void
            +eliminar(jugadorId: int, temporadaId: int, competicionId: int, equipoId: int): void
            +listar(): List<EstadisticasTemporada>

            +insertar(traspaso: Traspaso): void
            +modificar(traspaso: Traspaso): void
            +eliminar(idTraspaso: int): void
            +listar(): List<Traspaso>

            +insertar(valorMercadoHistorial: ValorMercadoHistorial): void
            +modificar(valorMercadoHistorial: ValorMercadoHistorial): void
            +eliminar(idHistorial: int): void
            +listar(): List<ValorMercadoHistorial>

            +insertar(noticia: Noticia): void
            +modificar(noticia: Noticia): void
            +eliminar(idNoticia: int): void
            +listar(): List<Noticia>

            +insertar(usuario: Usuario): void
            +modificar(usuario: Usuario): void
            +eliminar(idUsuario: int): void
            +listar(): List<Usuario>

            +insertar(equipoEntrenador: EquipoEntrenador): void
            +modificar(equipoEntrenador: EquipoEntrenador): void
            +eliminar(entrenadorId: int, equipoId: int): void
            +listar(): List<EquipoEntrenador>

            +List<EstadisticasTotales> listarTodos();
            +List<EstadisticasTotales> buscarPorJugador(String nombreJugador);
        }


    }

    TranferDAWDAO <|.. Database

}

package util{

    package input{
        component Input <<java>>
        interface Fichero {
            + leer(): byte[]
            + escribir(byte[])
        }
    }

    Fichero <|.. Input

}



package exception{
    component TransferDAWException <<java>>
}

package entity{

    component TransferDAW <<java>>
}

TransferDAWServlet ..> TransferDAW : use
TransferDAWServlet ..> Fichero : use
TransferDAWServlet ..> TranferDAWDAO : use


TransferDAWServlet ..> TransferDAWException : use
@enduml


