@startuml Diagrama de componentes

left to right direction

package "es.tierno.daw.transferdaw.view" {
    component TransferDAWHTML <<html>>
    component TransferDAWSCSS <<css>>
    component TransferDAWJS <<javascript>>
}

package "es.tierno.daw.transferdaw.controller" {
    component TransferDAWServlet <<servlet>>
}

TransferDAWHTML ..> TransferDAWServlet : solicita datos
TransferDAWJS ..> TransferDAWServlet : hace solicitudes dinámicas

package "es.tierno.daw.transferdaw.model"{
    component TransferDAW

    package bbdd {

        [TransferDAWJDBC] <<java>>

        [TransferDAWDAO] <<interface>>
    }

    package util{
        package input{
            component Input <<java>>
        }
    }

    package exception{
        component TransferDAWException <<java>>
    }

    package entity{
        component TransferDAWEntity <<java>>
    }

}

TransferDAWServlet --> TransferDAW : manages
TransferDAW --> TransferDAWDAO : uses
TransferDAWJDBC -|> TransferDAWDAO

@enduml


@startuml disenyo
allow_mixing
top to bottom direction
package "view" {
    component TransferDAWHTML <<html>>
    component TransferDAWSCSS <<css>>
    component TransferDAWJS <<javascript>>
}

package "controller" {
    component TransferDAWServlet <<servlet>>
}

TransferDAWHTML ..> TransferDAWServlet : solicita datos
TransferDAWJS ..> TransferDAWServlet : hace solicitudes dinámicas

package "model"{

    package bbdd{
        component Database <<java>>

        interface TransferDAWDAO{
        
        }

        TransferDAWDAO <|.. Database 
    }

    package util{

        package input{
            component Input <<java>>
            interface Fichero {
                + leer(): byte[]
                + escribir(byte[])
            }
        } 
        Fichero <|.. Input  

    }

    

    package exception{
        component TransferDAWException <<java>>
    }

    package entity{
        interface ITransferDAW{
            
        }

        component TransferDAW <<java>>

        ITransferDAW <|.. TransferDAW
    }
}

TransferDAWServlet ..> ITransferDAW : use
TransferDAWServlet ..> Fichero : use
TransferDAWServlet ..> TransferDAWDAO : use
@enduml


