.TH "es.tierno.daw.trasnferdaw.model.bbdd.TransferDAWDBFactory" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.bbdd.TransferDAWDBFactory
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTransferDAWDAO\fP \fBobtener\fP (\fBDatabase\fP tipo)  throws Exception "
.br
.in -1c
.SH "Detailed Description"
.PP 
La clase \fBTransferDAWDBFactory\fP crea las posibles BD disponibles\&. 
.PP
\fBAuthor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
