.TH "es.tierno.daw.trasnferdaw.model.bbdd.Database" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.bbdd.Database
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMARIADB\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
La enumeración TransferDAWDBactory posee las posibles BD disponibles\&. 
.PP
\fBAuthor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
