.TH "es.tierno.daw.trasnferdaw.model.entities.Equipo" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.entities.Equipo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEquipo\fP ()  throws BBDDException "
.br
.ti -1c
.RI "\fBEquipo\fP (String nombre, String ciudad, String pais, int anioFundacion, double presupuesto, String propietario, String estadioNombre, String entrenadorNombre)  throws BBDDException "
.br
.ti -1c
.RI "\fBEquipo\fP (Integer idEquipo, String nombre, String ciudad, String pais, int anioFundacion, double presupuesto, String propietario, String estadioNombre, String entrenadorNombre)  throws BBDDException "
.br
.ti -1c
.RI "Integer \fBgetIdEquipo\fP ()"
.br
.ti -1c
.RI "void \fBsetIdEquipo\fP (Integer idEquipo)"
.br
.ti -1c
.RI "String \fBgetNombre\fP ()"
.br
.ti -1c
.RI "void \fBsetNombre\fP (String nombre)"
.br
.ti -1c
.RI "String \fBgetCiudad\fP ()"
.br
.ti -1c
.RI "void \fBsetCiudad\fP (String ciudad)"
.br
.ti -1c
.RI "String \fBgetPais\fP ()"
.br
.ti -1c
.RI "void \fBsetPais\fP (String pais)"
.br
.ti -1c
.RI "int \fBgetAnioFundacion\fP ()"
.br
.ti -1c
.RI "void \fBsetAnioFundacion\fP (int anioFundacion)"
.br
.ti -1c
.RI "double \fBgetPresupuesto\fP ()"
.br
.ti -1c
.RI "void \fBsetPresupuesto\fP (double presupuesto)"
.br
.ti -1c
.RI "String \fBgetPropietario\fP ()"
.br
.ti -1c
.RI "void \fBsetPropietario\fP (String propietario)"
.br
.ti -1c
.RI "String \fBgetEstadioNombre\fP ()"
.br
.ti -1c
.RI "void \fBsetEstadioNombre\fP (String estadioNombre)"
.br
.ti -1c
.RI "String \fBgetEntrenadorNombre\fP ()"
.br
.ti -1c
.RI "void \fBsetEntrenadorNombre\fP (String entrenadorNombre)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
La clase \fBEquipo\fP representa un equipo de TransferDAW\&. 
.PP
\fBAuthor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.Equipo\&.Equipo () throws \fBBBDDException\fP"
Constructor por defecto de la clase \fBEquipo\fP\&. Inicializa una nueva instancia sin establecer valores para sus atributos\&.
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP

.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.Equipo\&.Equipo (String nombre, String ciudad, String pais, int anioFundacion, double presupuesto, String propietario, String estadioNombre, String entrenadorNombre) throws \fBBBDDException\fP"
Constructor que inicializa un equipo con sus datos básicos, sin especificar el ID\&.
.PP
\fBParameters\fP
.RS 4
\fInombre\fP Nombre del equipo 
.br
\fIciudad\fP Ciudad a la que pertenece el equipo 
.br
\fIpais\fP País del equipo 
.br
\fIanioFundacion\fP Año en que fue fundado el equipo 
.br
\fIpresupuesto\fP Presupuesto económico del equipo 
.br
\fIpropietario\fP Nombre del propietario del equipo 
.br
\fIestadioNombre\fP Nombre del estadio del equipo 
.br
\fIentrenadorNombre\fP Nombre del entrenador del equipo 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP

.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.Equipo\&.Equipo (Integer idEquipo, String nombre, String ciudad, String pais, int anioFundacion, double presupuesto, String propietario, String estadioNombre, String entrenadorNombre) throws \fBBBDDException\fP"
Constructor que inicializa un equipo incluyendo su identificador único\&.
.PP
\fBParameters\fP
.RS 4
\fIidEquipo\fP ID único del equipo 
.br
\fInombre\fP Nombre del equipo 
.br
\fIciudad\fP Ciudad a la que pertenece el equipo 
.br
\fIpais\fP País del equipo 
.br
\fIanioFundacion\fP Año en que fue fundado el equipo 
.br
\fIpresupuesto\fP Presupuesto económico del equipo 
.br
\fIpropietario\fP Nombre del propietario del equipo 
.br
\fIestadioNombre\fP Nombre del estadio del equipo 
.br
\fIentrenadorNombre\fP Nombre del entrenador del equipo 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
