.TH "es.tierno.daw.trasnferdaw.model.entities.Competicion" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.entities.Competicion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompeticion\fP ()  throws BBDDException "
.br
.ti -1c
.RI "\fBCompeticion\fP (String nombre, String pais, String tipo, int numeroEquipos, int anioCreacion)  throws BBDDException "
.br
.ti -1c
.RI "\fBCompeticion\fP (Integer idCompeticion, String nombre, String pais, String tipo, int numeroEquipos, int anioCreacion)  throws BBDDException "
.br
.ti -1c
.RI "Integer \fBgetIdCompeticion\fP ()"
.br
.ti -1c
.RI "void \fBsetIdCompeticion\fP (Integer idCompeticion)"
.br
.ti -1c
.RI "String \fBgetNombre\fP ()"
.br
.ti -1c
.RI "void \fBsetNombre\fP (String nombre)"
.br
.ti -1c
.RI "String \fBgetPais\fP ()"
.br
.ti -1c
.RI "void \fBsetPais\fP (String pais)"
.br
.ti -1c
.RI "String \fBgetTipo\fP ()"
.br
.ti -1c
.RI "void \fBsetTipo\fP (String tipo)"
.br
.ti -1c
.RI "int \fBgetNumeroEquipos\fP ()"
.br
.ti -1c
.RI "void \fBsetNumeroEquipos\fP (int numeroEquipos)"
.br
.ti -1c
.RI "int \fBgetAnioCreacion\fP ()"
.br
.ti -1c
.RI "void \fBsetAnioCreacion\fP (int anioCreacion)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
La clase \fBCompeticion\fP representa una competición de TransferDAW\&. 
.PP
\fBAuthor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.Competicion\&.Competicion () throws \fBBBDDException\fP"
Constructor por defecto de la clase \fBCompeticion\fP\&. Inicializa una nueva instancia sin establecer valores para sus atributos\&.
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP

.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.Competicion\&.Competicion (String nombre, String pais, String tipo, int numeroEquipos, int anioCreacion) throws \fBBBDDException\fP"
Constructor que inicializa una competición con sus datos básicos, sin especificar el ID\&.
.PP
\fBParameters\fP
.RS 4
\fInombre\fP Nombre de la competición 
.br
\fIpais\fP País donde se celebra la competición 
.br
\fItipo\fP Tipo de competición (por ejemplo, liga, copa, etc\&.) 
.br
\fInumeroEquipos\fP Número de equipos que participan en la competición 
.br
\fIanioCreacion\fP Año en el que se creó la competición 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP

.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.Competicion\&.Competicion (Integer idCompeticion, String nombre, String pais, String tipo, int numeroEquipos, int anioCreacion) throws \fBBBDDException\fP"
Constructor que inicializa una competición incluyendo su identificador único\&.
.PP
\fBParameters\fP
.RS 4
\fIidCompeticion\fP ID único de la competición 
.br
\fInombre\fP Nombre de la competición 
.br
\fIpais\fP País donde se celebra la competición 
.br
\fItipo\fP Tipo de competición (por ejemplo, liga, copa, etc\&.) 
.br
\fInumeroEquipos\fP Número de equipos que participan en la competición 
.br
\fIanioCreacion\fP Año en el que se creó la competición 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
