.TH "es.tierno.daw.trasnferdaw.model.bbdd.TransferDAWDAOImp" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.bbdd.TransferDAWDAOImp
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBes\&.tierno\&.daw\&.trasnferdaw\&.model\&.bbdd\&.TransferDAWDAO\fP\&.
.PP
Inherited by \fBes\&.tierno\&.daw\&.trasnferdaw\&.model\&.bbdd\&.TransferDAOImpMariaDB\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Connection \fBconn\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
La clase \fBTransferDAWDAOImp\fP servirá para futuras actualizaciones\&. 
.PP
\fBAuthor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
