.TH "es.tierno.daw.trasnferdaw.model.exception.BBDDException" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.exception.BBDDException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBes\&.tierno\&.daw\&.trasnferdaw\&.model\&.exception\&.TransferDAWException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBBDDException\fP (String message, Throwable cause)"
.br
.ti -1c
.RI "\fBBBDDException\fP (String message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
