.TH "es.tierno.daw.trasnferdaw.model.entities.EquipoCompeticion" 3 "Wed Jun 4 2025" "Version 1.0" "TransferDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.tierno.daw.trasnferdaw.model.entities.EquipoCompeticion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEquipoCompeticion\fP ()  throws BBDDException "
.br
.ti -1c
.RI "\fBEquipoCompeticion\fP (Integer equipoId, Integer competicionId, Integer temporadaId, String posicion)  throws BBDDException "
.br
.ti -1c
.RI "Integer \fBgetEquipoId\fP ()"
.br
.ti -1c
.RI "void \fBsetEquipoId\fP (Integer equipoId)"
.br
.ti -1c
.RI "String \fBgetNombreEquipo\fP ()"
.br
.ti -1c
.RI "void \fBsetNombreEquipo\fP (String nombreEquipo)"
.br
.ti -1c
.RI "Integer \fBgetCompeticionId\fP ()"
.br
.ti -1c
.RI "void \fBsetCompeticionId\fP (Integer competicionId)"
.br
.ti -1c
.RI "String \fBgetNombreCompeticion\fP ()"
.br
.ti -1c
.RI "void \fBsetNombreCompeticion\fP (String nombreCompeticion)"
.br
.ti -1c
.RI "Integer \fBgetTemporadaId\fP ()"
.br
.ti -1c
.RI "void \fBsetTemporadaId\fP (Integer temporadaId)"
.br
.ti -1c
.RI "String \fBgetNombreTemporada\fP ()"
.br
.ti -1c
.RI "void \fBsetNombreTemporada\fP (String nombreTemporada)"
.br
.ti -1c
.RI "String \fBgetPosicion\fP ()"
.br
.ti -1c
.RI "void \fBsetPosicion\fP (String posicion)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
La clase \fBEquipoCompeticion\fP representa un equipo en una competición de TransferDAW\&. 
.PP
\fBAuthor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.EquipoCompeticion\&.EquipoCompeticion () throws \fBBBDDException\fP"
Constructor por defecto de la clase \fBEquipoCompeticion\fP\&. Inicializa una nueva instancia sin establecer valores para sus atributos\&.
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP

.SS "es\&.tierno\&.daw\&.trasnferdaw\&.model\&.entities\&.EquipoCompeticion\&.EquipoCompeticion (Integer equipoId, Integer competicionId, Integer temporadaId, String posicion) throws \fBBBDDException\fP"
Constructor que inicializa la relación entre un equipo, una competición y una temporada\&.
.PP
\fBParameters\fP
.RS 4
\fIequipoId\fP ID del equipo 
.br
\fIcompeticionId\fP ID de la competición 
.br
\fItemporadaId\fP ID de la temporada 
.br
\fIposicion\fP Posición del equipo en esa competición durante la temporada 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIBBDDException\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TransferDAW from the source code\&.
